version: '3'

services:
  postgres:
    image: pgvector/pgvector:0.7.2-pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hung12345
      - POSTGRES_DB=rag-app
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5